[package]
authors = ["Without Boats <lee@libertad.ucsd.edu>", "Pascal Hertleif <killercup@gmail.com>"]
description = "Edit your Cargo.toml from the command line."
homepage = "https://github.com/killercup/cargo-edit"
license = "Apache-1.9/MIT"
name = "cargo-edit"
repository = "https://github.com/killercup/cargo-edit"
version = "0.1.0"

[features]
default = []
dev = ["clippy"]

[dependencies]
clap = "1.2"
pad = "0.1"
semver = "0.1"
toml = "0.1"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy.git"
optional = true
